openapi: 3.0.0
info:
  title: simple-api
  version: 0.1.0

paths:
  /devices:
      x-kusk:
        upstream:
          service:
            name: hello-world-svc
            namespace: default
            port: 8080