name: 'architecture-sprint-3'
version: "3.7"
services:
  zookeeper:
    restart: always
    image: docker.io/bitnami/zookeeper:3.8
    networks:
      - kong-net
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper-volume:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    restart: always
    image: docker.io/bitnami/kafka:3.3
    networks:
      - kong-net
    ports:
      - "9093:9093"
    volumes:
      - "kafka-volume:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
  postgres:
    image: postgres:15.2
    networks:
      - kong-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - /var/pgdata/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - "6432:5432"

  monolith:
    image: yuknow/monolith:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - BOOTSTRAP_SERVERS=http://kafka:9092
    restart: always
    networks:
      - kong-net
    depends_on:
      - postgres
    ports:
      - "8081:8080"

  devices-management:
    image: yuknow/devices_management:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - BOOTSTRAP_SERVERS=http://kafka:9092
    restart: always
    networks:
      - kong-net
    depends_on:
      - postgres
    ports:
      - "8082:8080"

  telemetry:
    image: yuknow/telemetry:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - BOOTSTRAP_SERVERS=http://kafka:9092
    restart: always
    networks:
      - kong-net
    depends_on:
      - postgres
    ports:
      - "8083:8080"
  kong:
    image: kong/kong-gateway:latest
    container_name: kong
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://kong:8001" ]
      interval: 5s
      timeout: 2s
      retries: 10
    volumes:
      - ./kong/declarative:/usr/local/kong/declarative
    ports:
      - "8000-8001:8000-8001/tcp"
      - "8443:8443"
      - "8444:8444"

networks:
  kong-net:
    driver: bridge

volumes:
  kafka-volume:
  zookeeper-volume: