@startuml
title SmartHome Telemetry Service ER Diagram

top to bottom direction

entity Device {
    * id: uuid
    --
    * user_id: uuid
    * model: string
}

entity Sensor {
    * device_id: uuid
    --
    * url: string
}

Sensor }|..|| Device
@enduml