@startuml
title SmartHome Component Diagram

top to bottom direction

!include C4/C4_Component.puml

Container_Boundary(SmartHomeSystem, "SmartHome System") {
  Container(DeviceManagement, "Device Management Service", "Java, Spring", "Управление списком устройств пользователя")
  Container(Telemetry, "Telemetry Service", "Java, Spring", "Сервис сбора данных датчиков")

  ContainerDb(DeviceManagementDb, "Database", "PostgreSQL", "Хранение информации об устройствах")
  ContainerDb(TelemetryDb, "Telemetry DB", "PostgreSQL", "Хранит информацию о зарегистрированных датчиках")

  ContainerQueue(Kafka, "Kafka", "Kafka", "Брокер сообщений")
}

Container(DeviceManagement, "Web Application", "Java, Spring") {
  Component(AddHomeCommandController, "Add Home Command controller", "Позволяет пользователю добавить новый дом")
  Component(RemoveHomeCommandController, "Remove Home Command controller", "Позволяет пользователю удалить дом")
  Component(AddDeviceCommandController, "Add Device Command controller", "Позволяет пользователю добавить новое устройство")
  Component(RemoveDeviceCommandController, "Remove Device Command controller", "Позволяет пользователю удалить устройство")
  Component(HomeQueryController, "Home Query controller", "Позволяет выполнить запросы для получения информации об домах")
  Component(DeviceQueryController, "Device Query controller", "Позволяет выполнить запросы для получения информации об устройствах")

  Component(AddHomeCommandHandler, "Add Home Command handler", "Обработчик команды добавления нового дома")
  Component(RemoveHomeCommandHandler, "Remove Home Command handler", "Обработчик команды удаления дома")
  Component(AddDeviceCommandHandler, "Add Device Command handler", "Обработчик команды добавления нового устройства")
  Component(RemoveDeviceCommandHandler, "Remove Device Command handler", "Обработчик команды удаления устройства")

  Component(HomeRepository, "Home Repository", "Репозиторий для работы с таблицей home")
  Component(DeviceRepository, "Device Repository", "Репозиторий для работы с таблицей device")

  Component(HomeQueryRepository, "Home Query Repository", "Репозиторий для получения данных о домах")
  Component(DeviceQueryRepository, "Device Query Repository", "Репозиторий для получения данных об устройствах")

  Rel(AddHomeCommandController,AddHomeCommandHandler,"Вызов обработчика команды")
  Rel(RemoveHomeCommandController,RemoveHomeCommandHandler,"Вызов обработчика команды")
  Rel(AddDeviceCommandController,AddDeviceCommandHandler,"Вызов обработчика команды")
  Rel(RemoveDeviceCommandController,RemoveDeviceCommandHandler,"Вызов обработчика команды")

  Rel(HomeQueryController,HomeQueryRepository,"Вызов репозитория")
  Rel(DeviceQueryController,DeviceQueryRepository,"Вызов репозитория")

  Rel(AddHomeCommandHandler,HomeRepository,"Добавление дома в таблицу бд")
  Rel(RemoveHomeCommandHandler,HomeRepository,"Удаление дома из таблицы в бд")
  Rel(AddDeviceCommandHandler,DeviceRepository,"Добавление устройства в таблицу бд")
  Rel(RemoveDeviceCommandHandler,DeviceRepository,"Удаление устройства из таблицы в бд")

  Rel(HomeRepository,DeviceManagementDb,"Вызов бд")
  Rel(DeviceRepository,DeviceManagementDb,"Вызов бд")
  Rel(HomeQueryRepository,DeviceManagementDb,"Получение данных из бд")
  Rel(DeviceQueryRepository,DeviceManagementDb,"Получение данных из бд")

  Rel(AddDeviceCommandHandler,Kafka,"Посылка команды на регистрацию нового устройства")
  Rel(RemoveDeviceCommandHandler,Kafka,"Посылка команды на удаление устройства")
}

Container(Telemetry, "Spring boot Application", "Java, Spring") {
    Component(CommonCommandHandler, "Common Command Handler", "Получает команды из кафки и вызывает нужный обработчик")

    Component(RegisterSensor, "Register Sensor Command Handler", "Обработчик команд на регистрацию новых датчиков")
    Component(RemoveSensor, "Remove Sensor Command Handler", "Обработчик команд на удаление датчиков")
    Component(TelemetryCollector, "Telemetry Collector", "Собирает данные с датчиков")

    Rel(CommonCommandHandler,RegisterSensor,"Вызов команды обработки регистрации датчика")
    Rel(CommonCommandHandler,RemoveSensor,"Вызов команды обработки удаления датчика")

    Rel(RegisterSensor,TelemetryDb,"Добавление нового датчика в таблицу")
    Rel(RemoveSensor,TelemetryDb,"Удаление датчика из таблицы")
    Rel(TelemetryCollector,TelemetryDb,"Получение информации текущих датчиках")

    Rel(CommonCommandHandler,Kafka,"Получение команд / отправка событий")
    Rel(TelemetryCollector,Kafka,"Отправка событий с данными телеметрии")
}
@enduml