@startuml
title SmartHome Telemetry History Service ER Diagram

top to bottom direction

entity TelemetryData {
    * device_id: uuid
    * datetime: datetime
    --
    * user_id: uuid
    * data: jsonb
}

@enduml