@startuml
title SmartHome Monolith Context Diagram

top to bottom direction

!include C4/C4_Context.puml
Person(user, "Пользователь", "Пользователь умного дома")
System(SmartHomeMonolith, "SmartHome Monolith", "Система удаленного управления отоплением в доме")

System_Ext(sensors, "Sensors", "Датчики температуры")
System_Ext(heatSystems, "Heat Systems", "Устройства отопления")

Rel(user, SmartHomeMonolith, "Управляет отоплением своего дома")
Rel(SmartHomeMonolith,sensors,"Получение данных о температуре с датчиков")
Rel(SmartHomeMonolith,heatSystems,"Управление устройствами отопления")

@enduml